---
title: "JOAHNY"
author: "Paul Joahny"
format: html
---

#Question 1
```{r}
library(here)
library(readr)
library(vroom)
here::i_am("grades-lab.Rproj")

courses <- vroom(here("Data", "courses.csv"))

```

#Question 2

```{r}

library(dplyr)
library(knitr)

courses |>
  arrange(course) |>
  rename(
    "course name" = course,
    "identifier" = course_id,
    "semester" = semester,
    "number of exams" = nb_grades
  ) |>
  kable()

```
#Question 3
```{r}


students <- vroom(
  here("Data", "students.csv"),
  col_types = cols(
    id = col_integer(),
    group = col_factor(),
    birth_date = col_date(),
    sex = col_factor()
  )
)
spec(students)

```
#Question 4
```{r}


grades <- read_delim(
  here("Data", "grades.csv"),
  delim = "|",
  na = "$",
  col_types = cols(
    id = col_integer(),
    course_id = col_integer(),
    grade = col_double()
  )
)


```

#Question 5
```{r}
library(ggplot2)

ggplot(students, aes(x = group)) +
  geom_bar()


```
#Question 6
```{r}
ggplot(students, aes(x = group, fill = sex)) +
  geom_bar(position = "fill")
```

#Question 7
First calculate age 
```{r}
library(lubridate)
library(dplyr)

students <- students |>
  mutate(age = time_length(today() - birth_date, unit = "year"))
```
```{r}
ggplot(students, aes(x = age)) +
  geom_density(bw = "sj") +
  geom_rug(alpha = 0.1)
```

#Question 8 

```{r}

median_age <- students |>
  summarise(
    median_age = round(median(age)),
    .by = group
  )

median_age |> kable()
```
#Question 9 
```{r}
library(dplyr)
library(knitr)
oldest <- students |>
  slice_max(age, n = 1, by = group) |>
  select(id, sex, age, group) |>
  arrange(desc(age))

oldest |> kable()
```

#Question 10 

```{r}

grade_count <- grades |>
  filter(!is.na(grade)) |>
  nrow()

```

The data set contains `r grade_count` grades.


#Question 11

```{r}


roman_avg <- grades |>
  inner_join(courses, by = "course_id") |>
  filter(course == "Roman Law and Jurisprudence") |>
  inner_join(students, by = "id") |>
  summarise(
    avg_grade = mean(grade, na.rm = TRUE),
    .by = group
  )
```

```{r}

ggplot(roman_avg, aes(x = group, y = avg_grade)) +
  geom_col()

```

#Question 12
```{r}

grades_sem <- grades |>
  inner_join(courses, by = "course_id") |>
  filter(!is.na(grade))

ggplot(grades_sem, aes(x = grade)) +
  geom_density(bw = "sj") +
  geom_rug(alpha = 0.1) +
  facet_wrap(vars(semester))

```

```{r}

library(dplyr)

grades_sem_count <- grades |>
  inner_join(courses, by = "course_id") |>
  filter(!is.na(grade)) |>
  summarise(
    n = n(),
    .by = semester
  )

grades_sem_count

```

